# Generated by Django 4.2.16 on 2026-05-05 09:47

import apps.comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("identifiant", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom_complet", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("resp_appro", "Resp. Approvisionnements / Adjoint"),
                            ("chef_cce", "Chef CCE"),
                            ("chef_slmg", "Chef SLMG"),
                            ("cg", "Controleur de Gestion"),
                            ("dfc", "Directeur Financier et Comptable"),
                            ("dg", "Directeur General"),
                            ("comptable", "Comptable Tresorerie"),
                            ("admin", "Administrateur Systeme"),
                            ("capteur", "Capteur IoT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                ("tentatives_echecs", models.PositiveSmallIntegerField(default=0)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "utilisateur",
            },
            managers=[
                ("objects", apps.comptes.models.UtilisateurManager()),
            ],
        ),
    ]
