# Generated by Django 4.2.16 on 2026-05-05 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jeton_jwt",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Jeton JWT (si API)",
                    ),
                ),
                (
                    "cle_session_django",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Cle session Django",
                    ),
                ),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", verbose_name="User-Agent navigateur"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ouverture de session"
                    ),
                ),
                (
                    "date_derniere_activite",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de derniere activite"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Session active"),
                ),
            ],
            options={
                "verbose_name": "Session utilisateur",
                "verbose_name_plural": "Sessions utilisateurs",
                "db_table": "session_utilisateur",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AlterModelOptions(
            name="utilisateur",
            options={
                "ordering": ["nom_complet"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="date_blocage",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de blocage automatique"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="date_dernier_echec",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date du dernier echec de connexion"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="date_derniere_connexion_reussie",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de derniere connexion reussie"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de derniere modification"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="motif_blocage",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Motif du blocage"
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="est_actif",
            field=models.BooleanField(
                default=True,
                help_text="Faux = compte bloque (apres 5 echecs).",
                verbose_name="Compte actif",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="identifiant",
            field=models.CharField(
                help_text="Login unique, sans espace.",
                max_length=50,
                unique=True,
                verbose_name="Identifiant de connexion",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Acces admin Django"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="nom_complet",
            field=models.CharField(max_length=150, verbose_name="Nom complet"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("resp_appro", "Resp. Approvisionnements / Adjoint"),
                    ("chef_cce", "Chef CCE"),
                    ("chef_slmg", "Chef SLMG"),
                    ("cg", "Controleur de Gestion"),
                    ("dfc", "Directeur Financier et Comptable"),
                    ("dg", "Directeur General"),
                    ("comptable", "Comptable Tresorerie"),
                    ("admin", "Administrateur Systeme"),
                    ("capteur", "Capteur IoT (token)"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Role metier",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="tentatives_echecs",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Tentatives echouees consecutives"
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(
                fields=["role", "est_actif"], name="utilisateur_role_630f32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(
                fields=["identifiant"], name="utilisateur_identif_c8d9f9_idx"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["utilisateur", "est_active"],
                name="session_uti_utilisa_53cf28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["date_expiration"], name="session_uti_date_ex_5be520_idx"
            ),
        ),
    ]
