# Generated by Django 4.2.16 on 2026-05-06 08:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        help_text="Format : FEB-AAAA-NNNN (genere automatiquement).",
                        max_length=20,
                        unique=True,
                        verbose_name="Numero de FEB",
                    ),
                ),
                (
                    "objet",
                    models.CharField(
                        help_text="Description courte de ce qui est demande.",
                        max_length=255,
                        verbose_name="Objet de la demande",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("EN_INSTANCE", "En instance de validation"),
                            ("VALIDEE", "Validee"),
                            ("MODIFIEE", "Modifiee"),
                            ("REJETEE", "Rejetee"),
                            ("SUPPRIMEE", "Supprimee"),
                            ("CLOTUREE", "Cloturee (montant <= 50 000 F)"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("MANUELLE", "Saisie manuelle"),
                            ("PREDICTION", "Generation automatique (prediction)"),
                        ],
                        default="MANUELLE",
                        max_length=20,
                        verbose_name="Origine",
                    ),
                ),
                (
                    "est_auto",
                    models.BooleanField(
                        default=False,
                        help_text="True si issue de la prediction des besoins.",
                        verbose_name="Generee automatiquement",
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant HT",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant TTC",
                    ),
                ),
                (
                    "motif_action",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Obligatoire pour les modifications, suppressions, rejets.",
                        verbose_name="Motif de la derniere action",
                    ),
                ),
                (
                    "est_supprimee",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Supprimee (suppression logique)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de creation"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de derniere modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feb_demandees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feb_recues",
                        to="referentiels.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feb_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validateur (CG ou DFC)",
                    ),
                ),
            ],
            options={
                "verbose_name": "FEB - Fiche d'Expression des Besoins",
                "verbose_name_plural": "FEB - Fiches d'Expression des Besoins",
                "db_table": "fiche_expression",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="LigneFiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_ligne",
                    models.CharField(
                        choices=[("ARTICLE", "Article"), ("SERVICE", "Service")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "designation_libre",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Si l'article/service n'est pas dans le catalogue.",
                        max_length=255,
                        verbose_name="Designation libre",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantite"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Prix unitaire HT"
                    ),
                ),
                (
                    "montant_ligne",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Montant ligne (qte * prix)",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_feb",
                        to="referentiels.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="approvisionnements.ficheexpression",
                        verbose_name="FEB liee",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_feb",
                        to="referentiels.serviceexterieur",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de FEB",
                "verbose_name_plural": "Lignes de FEB",
                "db_table": "ligne_fiche",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="ficheexpression",
            index=models.Index(
                fields=["statut", "est_supprimee"], name="fiche_expre_statut_7d2c31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ficheexpression",
            index=models.Index(
                fields=["demandeur", "statut"], name="fiche_expre_demande_af2a2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ficheexpression",
            index=models.Index(
                fields=["fournisseur"], name="fiche_expre_fournis_c20a4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ficheexpression",
            index=models.Index(
                fields=["-date_creation"], name="fiche_expre_date_cr_0cd9dd_idx"
            ),
        ),
    ]
