# Generated by Django 4.2.16 on 2026-05-06 09:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referentiels", "0001_initial"),
        ("approvisionnements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ficheexpression",
            options={
                "ordering": ["-date_creation"],
                "verbose_name": "FEB",
                "verbose_name_plural": "FEB",
            },
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="date_modification",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="date_suppression",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="date_validation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="demandeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feb_demandees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="est_auto",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="est_supprimee",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feb_recues",
                to="referentiels.fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="montant_ht",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="montant_ttc",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="montant_tva",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="motif_action",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="numero",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="objet",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="origine",
            field=models.CharField(
                choices=[
                    ("MANUELLE", "Saisie manuelle"),
                    ("PREDICTION", "Generation automatique (prediction)"),
                ],
                default="MANUELLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="statut",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("EN_INSTANCE", "En instance"),
                    ("VALIDEE", "Validee"),
                    ("MODIFIEE", "Modifiee"),
                    ("REJETEE", "Rejetee"),
                    ("SUPPRIMEE", "Supprimee"),
                    ("CLOTUREE", "Cloturee"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="taux_tva",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("18.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="ficheexpression",
            name="validateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feb_validees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_feb",
                to="referentiels.article",
            ),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="designation_libre",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="fiche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="approvisionnements.ficheexpression",
            ),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="montant_ligne",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="prix_unitaire",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="quantite",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_feb",
                to="referentiels.serviceexterieur",
            ),
        ),
        migrations.AlterField(
            model_name="lignefiche",
            name="type_ligne",
            field=models.CharField(
                choices=[("ARTICLE", "Article"), ("SERVICE", "Service")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="BonCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numero de BC",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_INSTANCE", "En instance"),
                            ("VALIDE", "Valide"),
                            ("SUPPRIME", "Supprime"),
                        ],
                        db_index=True,
                        default="EN_INSTANCE",
                        max_length=15,
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18.00"), max_digits=5
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "signe_en_po",
                    models.BooleanField(
                        default=False,
                        help_text="True si le DFC a signe a la place du DG.",
                        verbose_name="Signe en Pour Ordre (DFC pour DG)",
                    ),
                ),
                (
                    "est_verrouille",
                    models.BooleanField(
                        default=True,
                        help_text="True : champs metier non modifiables.",
                        verbose_name="Verrouille",
                    ),
                ),
                (
                    "est_envoye_fournisseur",
                    models.BooleanField(
                        default=False, verbose_name="BC envoye au fournisseur"
                    ),
                ),
                ("date_envoi_fournisseur", models.DateTimeField(blank=True, null=True)),
                ("motif_suppression", models.TextField(blank=True, default="")),
                ("est_supprime", models.BooleanField(db_index=True, default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("date_suppression", models.DateTimeField(blank=True, null=True)),
                (
                    "fiche",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bon_commande",
                        to="approvisionnements.ficheexpression",
                        verbose_name="FEB liee",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bc_recus",
                        to="referentiels.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bc_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validateur (DG ou DFC en PO)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de Commande",
                "verbose_name_plural": "Bons de Commande",
                "db_table": "bon_commande",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["statut", "est_supprime"],
                        name="bon_command_statut_d3349d_idx",
                    ),
                    models.Index(
                        fields=["fournisseur"], name="bon_command_fournis_95bb14_idx"
                    ),
                    models.Index(
                        fields=["-date_creation"], name="bon_command_date_cr_7d3a69_idx"
                    ),
                ],
            },
        ),
    ]
