# Generated by Django 4.2.16 on 2026-05-07 01:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("approvisionnements", "0002_alter_ficheexpression_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdrePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numero ordre de paiement",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant a payer"
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("INTEGRAL", "Paiement integral"),
                            ("ACOMPTE", "Acompte"),
                            ("SOLDE", "Solde"),
                        ],
                        default="INTEGRAL",
                        max_length=15,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Especes"),
                            ("CHEQUE", "Cheque"),
                            ("VIREMENT", "Virement bancaire"),
                            ("MOBILE_MONEY", "Mobile Money (Orange/Wave)"),
                        ],
                        default="VIREMENT",
                        max_length=15,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE_VISA", "En attente du visa DG"),
                            ("VISA_OK", "Visa accorde"),
                            ("REJETE_DG", "Rejete par DG"),
                        ],
                        db_index=True,
                        default="EN_ATTENTE_VISA",
                        max_length=20,
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Motif de l'ordre (ou motif de rejet si statut REJETE_DG).",
                    ),
                ),
                ("date_visa", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "bc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordres_paiement",
                        to="approvisionnements.boncommande",
                        verbose_name="Bon de Commande",
                    ),
                ),
                (
                    "dfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordres_emis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="DFC emetteur",
                    ),
                ),
                (
                    "dg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visas_donnes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="DG visa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordre de paiement",
                "verbose_name_plural": "Ordres de paiement",
                "db_table": "ordre_paiement",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numero de paiement",
                    ),
                ),
                (
                    "montant_verse",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant verse"
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("INTEGRAL", "Paiement integral"),
                            ("ACOMPTE", "Acompte"),
                            ("SOLDE", "Solde"),
                        ],
                        default="INTEGRAL",
                        max_length=15,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Especes"),
                            ("CHEQUE", "Cheque"),
                            ("VIREMENT", "Virement bancaire"),
                            ("MOBILE_MONEY", "Mobile Money (Orange/Wave)"),
                        ],
                        default="VIREMENT",
                        max_length=15,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="N° cheque, ID transaction, ref virement, etc.",
                        max_length=100,
                    ),
                ),
                ("est_acompte", models.BooleanField(default=False)),
                (
                    "solde_restant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Solde restant a payer (calcule auto).",
                        max_digits=12,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente d'execution"),
                            ("ACOMPTE", "Acompte verse"),
                            ("PAYE", "Paye integralement"),
                            ("REJETE", "Rejete (montant incorrect)"),
                        ],
                        db_index=True,
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("motif_rejet", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_execution", models.DateTimeField(blank=True, null=True)),
                (
                    "bc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="approvisionnements.boncommande",
                        verbose_name="Bon de Commande",
                    ),
                ),
                (
                    "comptable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements_executes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comptable executeur",
                    ),
                ),
                (
                    "ordre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="approvisionnements.ordrepaiement",
                        verbose_name="Ordre de paiement lie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "db_table": "paiement",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(fields=["statut"], name="paiement_statut_a0acf1_idx"),
                    models.Index(fields=["bc"], name="paiement_bc_id_03fc60_idx"),
                    models.Index(
                        fields=["-date_creation"], name="paiement_date_cr_1a87d7_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ordrepaiement",
            index=models.Index(fields=["statut"], name="ordre_paiem_statut_c984c7_idx"),
        ),
        migrations.AddIndex(
            model_name="ordrepaiement",
            index=models.Index(fields=["bc"], name="ordre_paiem_bc_id_db755d_idx"),
        ),
        migrations.AddIndex(
            model_name="ordrepaiement",
            index=models.Index(
                fields=["-date_creation"], name="ordre_paiem_date_cr_bafecd_idx"
            ),
        ),
    ]
