# Generated by Django 4.2.16 on 2026-05-08 10:26

import apps.extensions.iot.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneGeographique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la zone"
                    ),
                ),
                ("batiment", models.CharField(max_length=100, verbose_name="Batiment")),
                (
                    "etage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex : RDC, 1er, 2eme",
                        max_length=20,
                    ),
                ),
                (
                    "type_zone",
                    models.CharField(
                        choices=[
                            ("BUREAU", "Bureau"),
                            ("SALLE_INFORMATIQUE", "Salle informatique"),
                            ("SALLE_REUNION", "Salle de reunion"),
                            ("ENTREPOT", "Entrepot"),
                            ("SECURISE", "Zone securisee"),
                            ("EXTERIEUR", "Exterieur"),
                        ],
                        default="BUREAU",
                        max_length=25,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Coordonnees GPS",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "est_zone_autorisee",
                    models.BooleanField(
                        default=True,
                        help_text="Si False, tout equipement detecte ici declenche une alerte",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("est_active", models.BooleanField(db_index=True, default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zone geographique",
                "verbose_name_plural": "Zones geographiques",
                "db_table": "iot_zone_geographique",
                "ordering": ["batiment", "etage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=200, verbose_name="Designation"),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numero de serie"
                    ),
                ),
                (
                    "rfid_tag",
                    models.CharField(
                        help_text="Identifiant unique du tag",
                        max_length=64,
                        unique=True,
                        verbose_name="Tag RFID/BLE",
                    ),
                ),
                (
                    "valeur_acquisition",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valeur d'acquisition (F CFA)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_SERVICE", "En service"),
                            ("EN_PANNE", "En panne"),
                            ("EN_MAINTENANCE", "En maintenance"),
                            ("SORTI_ZONE", "Sorti de zone autorisee"),
                            ("INACTIF", "Inactif"),
                        ],
                        db_index=True,
                        default="EN_SERVICE",
                        max_length=20,
                    ),
                ),
                (
                    "est_suivi_iot",
                    models.BooleanField(
                        default=True, help_text="Activer le suivi IoT en temps reel"
                    ),
                ),
                (
                    "acces_bloque",
                    models.BooleanField(
                        default=False, help_text="Bloquer l'equipement (anti-vol)"
                    ),
                ),
                (
                    "token_capteur",
                    models.CharField(
                        default=apps.extensions.iot.models._generer_token_capteur,
                        help_text="Token secret pour API capteur",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("derniere_detection", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipements_iot",
                        to="referentiels.fournisseur",
                    ),
                ),
                (
                    "zone_actuelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipements_presents",
                        to="iot.zonegeographique",
                        verbose_name="Zone actuelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipement IoT",
                "verbose_name_plural": "Equipements IoT",
                "db_table": "iot_equipement",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="AlerteIoT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_alerte",
                    models.CharField(
                        choices=[
                            ("GEOFENCING", "Sortie de zone non autorisee"),
                            ("SIGNAL_PERDU", "Signal capteur perdu"),
                            ("BATTERIE_FAIBLE", "Batterie capteur faible"),
                            ("NON_AUTORISE", "Mouvement non autorise"),
                        ],
                        default="GEOFENCING",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("est_traitee", models.BooleanField(db_index=True, default=False)),
                ("commentaire_traitement", models.TextField(blank=True, default="")),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "equipement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="iot.equipement",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_iot_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone_actuelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alertes_zone_actuelle",
                        to="iot.zonegeographique",
                    ),
                ),
                (
                    "zone_quittee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alertes_zone_quittee",
                        to="iot.zonegeographique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte IoT",
                "verbose_name_plural": "Alertes IoT",
                "db_table": "iot_alerte",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "signal_force",
                    models.IntegerField(
                        default=100, help_text="Force du signal (0-100)"
                    ),
                ),
                (
                    "capteur_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID du capteur ayant detecte",
                        max_length=50,
                    ),
                ),
                (
                    "est_alerte",
                    models.BooleanField(
                        default=False, help_text="True si zone non autorisee"
                    ),
                ),
                (
                    "equipement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localisations",
                        to="iot.equipement",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="localisations",
                        to="iot.zonegeographique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localisation",
                "verbose_name_plural": "Localisations",
                "db_table": "iot_localisation",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="iot_localis_timesta_08b8f3_idx"
                    ),
                    models.Index(
                        fields=["equipement", "-timestamp"],
                        name="iot_localis_equipem_5124cd_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="equipement",
            index=models.Index(fields=["statut"], name="iot_equipem_statut_c208d3_idx"),
        ),
        migrations.AddIndex(
            model_name="equipement",
            index=models.Index(
                fields=["est_suivi_iot"], name="iot_equipem_est_sui_9b8d9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerteiot",
            index=models.Index(
                fields=["est_traitee"], name="iot_alerte_est_tra_a11dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerteiot",
            index=models.Index(
                fields=["-timestamp"], name="iot_alerte_timesta_bf7b1f_idx"
            ),
        ),
    ]
