# Generated by Django 4.2.16 on 2026-05-05 18:30

import apps.referentiels.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceExterieur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="Designation du service",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description detaillee"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cree par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service exterieur",
                "verbose_name_plural": "Services exterieurs",
                "db_table": "service_exterieur",
                "ordering": ["designation"],
            },
        ),
        migrations.CreateModel(
            name="Devise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex : XOF, EUR, USD",
                        max_length=5,
                        unique=True,
                        verbose_name="Code ISO",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Ex : Franc CFA BCEAO",
                        max_length=100,
                        verbose_name="Libelle",
                    ),
                ),
                (
                    "symbole",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex : F CFA, €, $",
                        max_length=10,
                        verbose_name="Symbole",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="Taux Senegal autorises : 0, 10, 18.",
                        max_digits=5,
                        verbose_name="Taux TVA applicable (%)",
                    ),
                ),
                (
                    "est_devise_principale",
                    models.BooleanField(
                        default=False,
                        help_text="Une seule devise peut etre principale.",
                        verbose_name="Devise principale",
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "gere_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devises_gerees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geree par (DFC)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
                "db_table": "devise",
                "ordering": ["-est_devise_principale", "code"],
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        help_text="Genere automatiquement (F0001, F0002...).",
                        max_length=10,
                        unique=True,
                        verbose_name="Code fournisseur",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "type_personne",
                    models.CharField(
                        choices=[
                            ("physique", "Personne physique"),
                            ("morale", "Personne morale"),
                        ],
                        default="morale",
                        max_length=10,
                        verbose_name="Type de personne",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Telephone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Utilise pour l'envoi des Bons de Commande.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        blank=True, default="", verbose_name="Adresse postale"
                    ),
                ),
                (
                    "ninea",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Numero d'Identification Nationale des Entreprises et Associations.",
                        max_length=50,
                        verbose_name="NINEA",
                    ),
                ),
                (
                    "rccm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Registre du Commerce et du Credit Mobilier.",
                        max_length=50,
                        verbose_name="RCCM",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fournisseurs_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cree par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "db_table": "fournisseur",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["nom"], name="fournisseur_nom_29e4aa_idx"),
                    models.Index(
                        fields=["est_actif"], name="fournisseur_est_act_f2c76e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Nom unique de l'article",
                        max_length=200,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("unite", "Unite"),
                            ("piece", "Piece"),
                            ("kilo", "Kilogramme (kg)"),
                            ("litre", "Litre (L)"),
                            ("metre", "Metre (m)"),
                            ("metre_carre", "Metre carre (m²)"),
                            ("boite", "Boite"),
                            ("paquet", "Paquet"),
                            ("lot", "Lot"),
                            ("heure", "Heure"),
                        ],
                        default="unite",
                        max_length=20,
                        verbose_name="Unite de mesure",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("fourniture_bureau", "Fourniture de bureau"),
                            ("equipement_info", "Equipement informatique"),
                            ("mobilier", "Mobilier"),
                            ("consommable", "Consommable"),
                            ("materiel_tech", "Materiel technique"),
                            ("produit_entretien", "Produit d'entretien"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        default="autre",
                        max_length=30,
                        verbose_name="Nature",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Description complementaire",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Format JPG, PNG ou WebP. Max 5 Mo.",
                        null=True,
                        upload_to=apps.referentiels.models.chemin_image_article,
                        verbose_name="Image de l'article",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(
                        default=True,
                        help_text="Faux = article retire du catalogue (suppression logique).",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de creation"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de derniere modification"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cree par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "article",
                "ordering": ["designation"],
                "indexes": [
                    models.Index(
                        fields=["nature", "est_actif"], name="article_nature_50949a_idx"
                    ),
                    models.Index(
                        fields=["designation"], name="article_designa_9edae2_idx"
                    ),
                ],
            },
        ),
    ]
