# Generated by Django 4.2.16 on 2026-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentiels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="derniere_alerte",
            field=models.DateTimeField(
                blank=True,
                help_text="Derniere fois qu'une alerte a ete declenchee (evite spam)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="gestion_stock_active",
            field=models.BooleanField(
                default=False,
                help_text="Si False, l'article n'est pas gere en stock (services, equipements uniques)",
                verbose_name="Gestion stock activee",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="quantite_a_commander",
            field=models.IntegerField(
                default=0,
                help_text="Quantite suggeree lors d'une commande automatique",
                verbose_name="Quantite a commander",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="quantite_stock",
            field=models.IntegerField(default=0, verbose_name="Quantite en stock"),
        ),
        migrations.AddField(
            model_name="article",
            name="seuil_alerte",
            field=models.IntegerField(
                default=0,
                help_text="Si quantite_stock <= seuil_alerte, alerte declenchee",
                verbose_name="Seuil d'alerte",
            ),
        ),
    ]
