# Generated by Django 4.2.16 on 2026-05-06 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notif",
                    models.CharField(
                        choices=[
                            ("FEB_SOUMISE", "FEB soumise"),
                            ("FEB_VALIDEE", "FEB validee"),
                            ("FEB_REJETEE", "FEB rejetee"),
                            ("FEB_CLOTUREE", "FEB cloturee"),
                            ("BC_GENERE", "BC genere automatiquement"),
                            ("BC_VALIDE", "BC valide"),
                            ("BC_ENVOYE", "BC envoye au fournisseur"),
                            ("INFO", "Information"),
                            ("AVERTISSEMENT", "Avertissement"),
                        ],
                        default="INFO",
                        max_length=30,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCES", "Succes"),
                            ("AVERTISSEMENT", "Avertissement"),
                            ("DANGER", "Danger"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("sujet", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("entite", models.CharField(blank=True, default="", max_length=50)),
                ("entite_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "url_action",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("est_lue", models.BooleanField(db_index=True, default=False)),
                ("email_envoye", models.BooleanField(default=False)),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_recues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_envoyees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Expediteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["destinataire", "est_lue"],
                        name="notificatio_destina_6ba390_idx",
                    ),
                    models.Index(
                        fields=["-date_creation"], name="notificatio_date_cr_bbd6c3_idx"
                    ),
                ],
            },
        ),
    ]
